baseURL = "https://jiwonkkang.github.io/"
languageCode = "zh-cn"
title = "MeiK's blog"
theme = "github-style"
googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "JiwonKKang"
  description = "In solitude, where we are least alone."
  github = "JiwonKKang"
  facebook = "JiwonKKang"
  twitter = "JiwonKKang"
  linkedin = "JiwonKKang"
  instagram = "JiwonKKang"
  tumblr = "JiwonKKang"
  email = "kangji149@naver.com"
  url = "https://jiwonkkang.github.io"
  utterances = "JiwonKKang/JiwonKKang.github.io"
  rss = true
  lastmod = true
  enableGitalk = true
    
  [params.gitalk]
    clientID = "5a1c911a3bb5ff14fe5e" # Your client ID
    clientSecret = "8586a43d9a15967e4760ef333ef31eab72c6d3ea" # Your client secret
    repo = "jiwonkkang.github.io" # 您的博客的github地址Repository name，例如：xxxx.github.io
    owner = "JiwonKKang" # 您的GitHub ID
    admin = "JiwonKKang" # 您的GitHub ID
    id = "location.pathname" # 文章页面的链接地址就是ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # 设置为true，如果是管理员登录，会自动创建issue，如果是false，需要管理员手动添加第一个评论(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
